[package]
name = "dumb_web_app"
version = "0.1.0"
authors = ["rasha <rashadmahmo@gmail.com>"]

[dependencies.rusqlite]
version = "*"
features = ["bundled"]

[dependencies]
csv = "1.0.0-beta.5"
serde = "1"
serde_derive = "1"